### ISSUE TITLE
Add device tree source

### ISSUE THREAD

**Issue by thinhtrongnguyen** [friendlyarm/linux-3.4.y#19]
I searched in linux-3.4.y/arch/arm/boot/dts. Unfortunately, I cannot find any device tree source for nanopi M3. Please add it to repository. Many thanks.

**Comment by igorpecovnik** [comment]
IIRC DT was introduced in 3.10 ... not present in 3.4.y

**Comment by thinhtrongnguyen** [comment]
Thanks for reply! So i have a question, how can it works without device tree? Can you give me a short explanation or a document that explains it?

**Comment by igorpecovnik** [comment]
Didn't work anything with this particular kernel but I can point you to two locations. First is an example how hardware config is solved in 3.4.y Allwinner http://linux-sunxi.org/Fex_Guide ... similar is solved on another platform. How exactly this is on M3 .. don't know, but there are alternatives. Community supported kernel 4.11.y https://github.com/rafaello7/linux-nanopi-m3 and apparently there is some 4.4.y from Samsung. https://www.cnx-software.com/2017/11/12/nanopi-fire2a-fire3-boards-released-with-samsungnexcell-quad-octa-core-processors/#comments I would not waste time with 3.4.y

**Comment by thinhtrongnguyen** [comment]
Thanks for the information.
