### ISSUE TITLE
怎么添加mali支持

### ISSUE THREAD

**Issue by lvzaina** [friendlyarm/linux-3.4.y#29]
你们提供的

>  http://112.124.9.243/qtsdk-friendlyelec/s5p4418/ 

里面，文件系统似乎是基于3.4的内核，用这个里面的rootfs，qt5deme打开报错
`Could not initialize egl display`
`/usr/bin/qt5demo: line 5:   774 Aborted                 ./QtE-Demo -qws`

看起来似乎是qt5依赖mali驱动，我只需要在3.4内核编译选项里打开mali支持？有没有更详细的支持，谢谢诸位

**Comment by lvzaina** [comment]
![image](https://user-images.githubusercontent.com/13482459/51440217-b75bdd80-1cff-11e9-863a-95b671a4f851.png)
我找到一个你们开发的回复，看起来要下载安卓代码来试试，不知道方向对不对，希望你们有空能回复我
 @911gt3

**Comment by friendlyarm** [comment]
可能是你下载的版本有点旧，请从这里下载最新的：http://dl.friendlyarm.com/QtSDK-FriendlyELEC

**Comment by lvzaina** [comment]
看修改时间是一样的，我重新下载你这个试试

**Comment by lvzaina** [comment]
@friendlyarm 下载了你说的，md5是一样的，还有什么建议，其实这个你能帮忙问下 @911gt3 这个老哥，一两句话就解决了

**Comment by lvzaina** [comment]
这个我下载了，对比md5和我下载是一样的，我对比了4.4内核，4.4内核是有/dev/mali节点的，和这个相关吗 @911gt3 , 怎么找到这个驱动

**Comment by friendlyarm** [comment]
3.4内核的mali驱动只支持android，如果要支持qt5的opengles，必须要使用4.4的内核。

**Comment by lvzaina** [comment]
能提供移植mali驱动的步骤吗？我这里不使用android

**Comment by friendlyarm** [comment]
非常抱歉，我们不是特别理解你的问题或是你想要达到的目的。
但是，现在发布的4.4内核的ROM，其qt5已经支持opengles，同时也提供了demo，对应的4.4内核源代码已经包含mali驱动，不需要额外的移植，谢谢！
4418/6818的4.4内核源代码是:
https://github.com/friendlyarm/linux/tree/nanopi2-v4.4.y

**Comment by lvzaina** [comment]
是我没说清楚，我们使用了你们4418的核心板，但是我们对比发现，4.4内核otg、ov5640等等几个重要的外设没有支持，看起来你们android都是用的3.4内核，这些支持相对完善，使用你们3.4内核这些都能驱动起来，但是我们的核心算法应用是需要opengles支持的，所以才有这些问题。我现在就是用3.4内核加上
> http://112.124.9.243/qtsdk-friendlyelec/s5p4418/rootfs-s5p4418.tgz

的文件系统，但是qt5demo跑不起来

**Comment by friendlyarm** [comment]
4.4内核的otg测试过可以正常工作，但是需要硬件也支持，ov5640也已经支持，gstreamer可预览。
3.4内核的mali驱动版本与4.4中的不同，只支持android，不支持qt5
因此，如果要使用opengles，需要使用4.4内核；如果你坚持要使用3.4内核，理论上可以将4.4内核的mali驱动移植到3.4内核，但是不一定能成功，我们也无法支持相关的支持。

**Comment by lvzaina** [comment]
有点尴尬
