### ISSUE TITLE
opengl怎么测试怎么使用

### ISSUE THREAD

**Issue by lvzaina** [friendlyarm/linux-3.4.y#30]
![image](https://user-images.githubusercontent.com/13482459/60383039-81850700-9a9e-11e9-948b-9bc2a3ab27dc.png)
现在我用的4.4的内核，想要测试opengl，你们能提供opengl的测试代码吗，我想让我的界面库加上gpu支持，能否提供思路

**Comment by friendlyarm** [comment]
http://wiki.friendlyarm.com/wiki/index.php/How_to_Build,_Install_and_Setting_Qt_Application/zh
